### PR TITLE
Use named export for ES module compatibility.

### PR DESCRIPTION
**Pull request by bradleyayers**
I'd expect a major bump after this is released.

### CODE REVIEW

**Comment by stephankaag** [comment]
@marijnh What do you think? I need this as well.

**Comment by marijnh** [comment]
Argh, sorry about never responding here.

In which context can you treat a CommonJS module as an ES module, but you can't use `module.exports` as `export default`?

**Comment by stephankaag** [comment]
Now it's my turn to Argh ;-)

I had a wrong import statement somewhere else and i (incorrectly) blamed ordermap. You can ignore my previous comment.

**Comment by marijnh** [comment]
Okay, thanks. @bradleyayers Is this still something that would help you? If not, I'll close it.

**Comment by bradleyayers** [comment]
I don't believe I need this since TypeScript added `esModuleInterop`.

**Pull request closed without merging**
